services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=8080
      # SendGrid vars - set these in a local .env file for local email testing
      # - SENDGRID_API_KEY=your_api_key_here
      # - SENDGRID_SENDER_EMAIL=your_email@gmail.com
    ports:
      - "8080:8080"