name: Website CI check

on:
  push:
    branches:
      - uat
      - main
  pull_request:
    branches:
      - uat
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Show all files
        run: |
          ls -la
          find . -maxdepth 3 -type f

      - name: Check required website files
        run: |
          test -f index.html
          test -f styles.css

      - name: Check HTML file is not empty
        run: |
          test -s index.html

      - name: Check CSS file is not empty
        run: |
          test -s styles.css